http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  loginUser:
    host: localhost
    paths: "/api/login"
    method: ["POST"]
  signupUser:
    host: localhost
    paths: "/api/signup"
    method: ["POST"]
  guestProfile:
    host: localhost
    paths: "/api/guestProfile/*"
    method: ["GET", "PUT"]
  ownerProfile:
    host: localhost
    paths: "/api/ownerProfile/*"
    method: ["GET", "PUT"]
  booking:
    host: localhost
    paths: "/api/booking/*"
    method: ["GET", "POST"]
  payment:
    host: localhost
    paths: "/api/payment/*"
    method: ["POST"]
  getPropertyByLocation:
    host: localhost
    paths: "/api/getPropertyByLocation/*"
    method: ["GET"]
  getProperty:
    host: localhost
    paths: "/api/getProperty/*"
    method: ["GET"]
  addProperty:
    host: localhost
    paths: "/api/addproperty"
    method: ["POST"]
  addImage:
    host: localhost
    paths: "/api/upload"
    method: ["POST"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  loginService:
    url: "http://localhost:4000"
  signupService:
    url: "http://localhost:4000"
  guestProfileService:
    url: "http://localhost:4000"
  ownerProfileService:
    url: "http://localhost:4000"
  bookingService:
    url: "http://localhost:4000"
  paymentService:
    url: "http://localhost:4000"
  getPropertyByLocationService:
    url: "http://localhost:4000"
  getPropertyService:
    url: "http://localhost:4000"
  addPropertyService:
    url: "http://localhost:4000"
  addImageService:
    url: "http://localhost:4000"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true

  loginPipeline:
    apiEndpoints:
      - loginUser
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: loginService
              changeOrigin: true

  signupPipeline:
    apiEndpoints:
      - signupUser
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: signupService
              changeOrigin: true

  guestProfilePipeline:
    apiEndpoints:
      - guestProfile
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: guestProfileService
              changeOrigin: true

  ownerProfilePipeline:
    apiEndpoints:
      - ownerProfile
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: ownerProfileService
              changeOrigin: true

  bookingPipeline:
    apiEndpoints:
      - booking
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: bookingService
              changeOrigin: true

  paymentPipeline:
    apiEndpoints:
      - payment
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: paymentService
              changeOrigin: true

  getPropertyByLocationPipeline:
    apiEndpoints:
      - getPropertyByLocation
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: getPropertyByLocationService
              changeOrigin: true

  getProperty:
    apiEndpoints:
      - getProperty
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: getPropertyService
              changeOrigin: true

  addProperty:
    apiEndpoints:
      - addProperty
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: addPropertyService
              changeOrigin: true

  addImage:
    apiEndpoints:
      - addImage
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: addImageService
              changeOrigin: true
